### ISSUE TITLE
Discussions Tab?

### ISSUE THREAD

**Issue by Ndrinta** [FozzieUK/FoxESS-Canbus-Protocol#2]
Hi, could you enable the Discussions section? I wanted to start logging my system soon and I'd like to talk about your setup (wiring, CAN logger device details) and software you used but I don't want to open "issues" for that...

**Comment by FozzieUK** [comment]
ok opened here https://github.com/FozzieUK/FoxESS-Canbus-Protocol/discussions

Let me know if you need anything else 👍

**Comment by Ndrinta** [comment]
Amazing, thanks!

(I'll stop being a pain in the a** now)
